name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Set env var
        run: |
          echo "VSS_ENV=test" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker test
        uses: you-win/godot-tester@feature/custom-godot-build
        with:
          version: "3.x"
          release_type: "stable"
          test-dir: "res://tests"
          custom-godot-dl-url: "https://github.com/virtual-puppet-project/godot/releases/download/latest/Godot_v3.x-stable_linux_headless.64.zip"
